"""LangGraph agent runner using gemini-3.1-flash-lite-preview.

This module exposes helpers to build and run a LangGraph ReAct agent.
Added: module-level logger and basic instrumentation for question quality checks.
"""
from typing import TypedDict, Any
import logging

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.prebuilt import create_react_agent
from langgraph.graph import StateGraph, END


MODEL_NAME = "gemini-3.1-flash-lite-preview"

class AgentState(TypedDict):
    stateStr: str
    question: str
    response: str

# Singleton cache for the compiled StateGraph app
_COMPILED_APP: Any = None


# Module-level logger. Applications can configure logging as desired. A small
# helper is provided below to set a basic configuration when needed.
logger = logging.getLogger(__name__)


def configure_logging(level: int = logging.INFO) -> None:
    """Configure a simple logging handler for this module if none exists.

    Call this from application startup if you want module-level logging output
    (e.g. configure_logging(logging.DEBUG)). It is safe to call multiple times.
    """
    if not logger.handlers:
        handler = logging.StreamHandler()
        formatter = logging.Formatter(
            "%(asctime)s %(levelname)s %(name)s: %(message)s"
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)
    logger.setLevel(level)

def return_good_poor(state: AgentState) -> str:
    # Return the label expected by StateGraph conditional edges ("GOOD"/"POOR").
    return "GOOD" if state.get("stateStr") == "GOOD" else "POOR"


def check_question_quality(state: AgentState) -> AgentState:
    """Updates the AgentState when the given question is labelled GOOD or POOR.

    The prompt expects a variable named `question` and we pass a mapping when
    invoking the runnable chain so templating resolves correctly.
    """
    gemini = ChatGoogleGenerativeAI(model=MODEL_NAME, temperature=0.0)
    prompt = ChatPromptTemplate.from_template(
        """
        Decide the quality of the question based on how easily an LLM can answer it.
        Answer only with GOOD or POOR.
        Question: {question}
        """
    )

    chain = prompt | gemini | StrOutputParser()

    q_text = state.get("question", "")
    logger.debug("Invoking quality-check chain for question: %s", q_text)
    # pass a mapping matching template variables
    answer = chain.invoke({"question": q_text})
    logger.debug("Raw answer from question quality chain: %r", answer)


    if answer == "GOOD" or answer == "POOR":
        return {**state, "stateStr": answer}
    logger.warning(
        "Unexpected label from model: %r. Defaulting to POOR", answer)
    return {**state, "stateStr": "POOR"}

def rewrite_question(state: AgentState) -> AgentState:
    """Updates the agent state to contain a question re-written by the LLM.

    Passes the current question into the prompt via the `question` variable.
    """
    gemini = ChatGoogleGenerativeAI(model=MODEL_NAME, temperature=0.2)
    prompt = ChatPromptTemplate.from_template(
        """
        The question has been rated to be poor quality.
        Please rewrite it so that it can be easily answered by an LLM, while preserving the original intent as much as possible.
        Question: {question}
        """
    )
    chain = prompt | gemini | StrOutputParser()
    q_text = state.get("question", "")
    new_question = chain.invoke({"question": q_text})
    logger.debug("Raw answer from rewrite question chain: %r", new_question)

    return {**state, "question": new_question, "stateStr": "READY"}

def check_hallucination(state: AgentState) -> AgentState:
    """Updates the state based on whether the answer was hallucinated or not."""
    gemini = ChatGoogleGenerativeAI(model=MODEL_NAME, temperature=0.0)
    prompt = ChatPromptTemplate.from_template(
        """
        You are a helpful agent. You are given a response that was generated by an LLM. You must decide whether the response is a hallucination or not. 
        A hallucination is a response that contains information that is not supported by the question or any provided context, and that cannot be verified as true. 
        Answer only with GOOD if the response is not a hallucination, and POOR if it is a hallucination.
        Response: {response}
        """
    )
    chain = prompt | gemini | StrOutputParser()
    resp_text = state.get("response", "")
    logger.debug("Invoking hallucination-check chain for response: %s", resp_text)
    answer = chain.invoke({"response": resp_text})
    logger.debug("Raw answer from check hallucination chain: %r", answer)
    if answer == "GOOD" or answer == "POOR":
        return {**state, "stateStr": answer }
    return {**state, "stateStr": "POOR"}


def generate_response(state: AgentState) -> AgentState:
    gemini = ChatGoogleGenerativeAI(model=MODEL_NAME, temperature=0.3)
    prompt = ChatPromptTemplate.from_template(
        """
        You are a helpful and courteous agent. You are given a question and you will answer accurately and concisely.
        Question: {question}
        """
    )
    chain = prompt | gemini | StrOutputParser()
    q_text = state.get("question", "")
    answer = chain.invoke({"question": q_text})
    logger.debug("Raw answer from generate chain: %r", answer)
    return {**state, "response": answer}

def create_graph() -> Any:
    """Create and compile the StateGraph app and cache it as a singleton.

    Subsequent calls return the cached compiled app instance.
    """
    global _COMPILED_APP
    if _COMPILED_APP is not None:
        return _COMPILED_APP

    graph = StateGraph(AgentState)
    graph.add_node("check_question_quality", check_question_quality)
    graph.add_node("rewrite_question", rewrite_question)
    graph.add_node("check_hallucination", check_hallucination)
    graph.add_node("generate_response", generate_response)
    graph.add_conditional_edges("check_question_quality", return_good_poor, {
        "GOOD": "generate_response",
        "POOR": "rewrite_question",
    })
    graph.add_conditional_edges("check_hallucination", return_good_poor, {
        "GOOD": END,
        "POOR": "generate_response",
    })
    graph.add_edge("rewrite_question", "generate_response")
    graph.add_edge("generate_response", "check_hallucination")
    graph.set_entry_point("check_question_quality")

    _COMPILED_APP = graph.compile()
    logger.debug("Compiled and cached StateGraph app")
    return _COMPILED_APP

def run_agent(query: str, agent_definition: str | None = None) -> str:
    """Run the agent with the given query.

    Args:
        query: The user question or instruction.
        agent_definition: Optional system prompt / instructions read from the
                          uploaded agent file.

    Returns:
        The agent's final response as a string.
    """

    app = create_graph()
    response = app.invoke({"question": query, "stateStr": "", "response": ""})
    return response.get("response", "")
